project:
  title: "scienceforfuture2023"
  output-dir: docs
  preview:
    port: 4200
    browser: true
    watch-inputs: true

execute:
  freeze: auto  # re-render only when source changes
  # cache: true

editor:
  render-on-save: true

format:
  revealjs:

    # embed-resources: true
    theme: [default,styles.scss]
    highlight-style: dracula
    code-line-numbers: true
    code-fold: false
    code-tools: true
    code-copy: true
    navigation-mode: vertical
    controls-layout: bottom-right
    controls-tutorial: true
    chalkboard:
      theme: whiteboard
