project:
  title: "scienceforfuture2023"
  output-dir: docs
  preview:
    port: 2222
    browser: true
    watch-inputs: true

execute:
  freeze: auto  # re-render only when source changes
  # cache: true

editor:
  render-on-save: true

format:
  revealjs:
    embed-resources: true
    theme: [simple,docs/styles.scss]
    highlight-style: dracula
    code-line-numbers: true
    code-fold: false
    code-tools: true
    code-copy: true
    navigation-mode: linear
    controls-layout: bottom-right
    controls-tutorial: true
    # chalkboard:
    #   theme: whiteboard
